version: "3"
services: 
  react-app:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - bitespeed-app
  api-server:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - bitespeed-app
  database:
    image: mongo
    ports: 
      - "27017:27017"
    networks:
      - bitespeed-app
    volumes:
      - ./data:/data/db

networks:
  bitespeed-app:
  
