services:

  - type: web
    name: react-app
    env: docker
    dockerfilePath: ./front-end/Dockerfile
    buildCommand: npm run build
    envVars:
      - key: PORT
        value: 3000

  - type: web
    name: api-server
    env: docker
    dockerfilePath: ./back-end/Dockerfile
    buildCommand: npm run build
    envVars:
      - key: PORT
        value: 8000
    startCommand: python3 wait-for-service.py database:27017 -- npm start

  - type: web
    name: database
    image: mongo